# 项目启动端口
server:
  port: 9999
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/android?serverTimezone=UTC&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: true

# 配置mybatis
mybatis:
  mapper-locations: classpath:com/mashibing/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true